/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_digitalcollections_iiif_image_backend_impl_repository_jpegtran_v2_EpegScaler */

#ifndef _Included_de_digitalcollections_iiif_image_backend_impl_repository_jpegtran_v2_EpegScaler
#define _Included_de_digitalcollections_iiif_image_backend_impl_repository_jpegtran_v2_EpegScaler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_digitalcollections_iiif_image_backend_impl_repository_jpegtran_v2_EpegScaler
 * Method:    downScaleJpegImage
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_digitalcollections_iiif_image_backend_impl_repository_jpegtran_v2_EpegScaler_downScaleJpegImage
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
